apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
  namespace: my-app-namespace
data:
  DATABASE_URL: "postgres://user:password@postgres-service:5432/mydb"
  LOG_LEVEL: "info"
  FEATURE_FLAG: "true"