apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
  namespace: my-app-namespace
type: Opaque
data:
  DATABASE_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded password
  API_KEY: YXBpS2V5MTIz  # Base64 encoded API key