apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: my-app-namespace
  labels:
    app: my-app
spec:
  replicas: 3  # Number of desired pods
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: my-app-image:latest  # Docker image to use
          ports:
            - containerPort: 8080  # Port that the container listens on
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: DATABASE_URL
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DATABASE_PASSWORD
