apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: my-app-namespace
  labels:
    app: my-app
spec:
  type: ClusterIP  # Change to LoadBalancer or NodePort as needed
  selector:
    app: my-app
  ports:
    - port: 80  # Port that the service will expose
      targetPort: 8080  # Port on the pod to forward traffic to
